### ISSUE TITLE
Greenify CI

### ISSUE THREAD

**Issue by curran** [kbadk/json0-ot-diff#20]
CI is set up, but broken. It would be neat to fix. Maybe easy? Not sure...

This is the error I see:

![image](https://user-images.githubusercontent.com/68416/142256889-e579a209-a9af-4554-b1a6-76ae1052e58b.png)

Here https://github.com/curran/json0-ot-diff/actions/runs/1472895879

It looks like it's trying to publish to NPM on each push?

**Comment by kbadk** [comment]
As far as I can tell, that error is happening in your fork of the repository. This fails, because you haven't defined an `NPM_TOKEN` secret for the repository. (Even if you had, it would fail anyway, because that token wouldn't have access to the NPM repository).

In this repository, `NPM_TOKEN` is defined and the GHA script does work.

>It looks like it's trying to publish to NPM on each push?

Yes, but when the version hasn't been bumped in `package.json`, the script gracefully terminates with a message such as:

>📦 json0-ot-diff v1.0.8 is already published to NPM

(Copied from the most recent workflow execution).

If you bumped the version in https://github.com/kbadk/json0-ot-diff/pull/19, for instance, and the PR then got merged in, it'd auto-publish.

I don't see anything broken here.

**Comment by curran** [comment]
Aha! Thank you for the investigation 🙏.

My mistake for not realizing this was in my fork only.
