### ISSUE TITLE
String Operations

### ISSUE THREAD

**Issue by curran** [kbadk/json0-ot-diff#4]
Greetings,

I'm wondering, would there be interest in optimizing the case where strings are mutated?

I have a use case where I'd like to preserve the historical ops for mutations on long strings. Currently if a string value is changed, the diff presents a combination of `oi` and `od`. This case could be optimized by computing a string diff and presenting the diff as string operations `si` and `sd`. The advantage of doing this would be that for large strings, less bandwidth would be used, and the persisted ops would be smaller.

I've researched this a bit, and also posted a [thread on the ShareDB mailing list](https://groups.google.com/forum/#!topic/sharejs/O8_fR4IIBlI). The library [JSDiff](https://github.com/kpdecker/jsdiff#api) has a function called `diffChars` whose output I _think_ can be translated directly into `si` and `sd` ops.

The disadvantage of doing this would be the additional dependency on JSDiff. Perhaps it could be implemented in such a way that the dependency is optional (e.g. if a reference to the `diffChars` function is passed in, then it's used, otherwise not).

Would such a contribution be welcome here? Thank you.

**Comment by kbadk** [comment]
Hi Curran,

Thank you for your interest in contributing, it's much appreciated!

That would indeed be very possible and it's also something I contemplated myself when implementing it. After all, I developed this package to be used with [Webstrates](https://github.com/Webstrates/Webstrates) where we [are already calculating string diffs](https://github.com/Webstrates/Webstrates/blob/9ddb44164110f21ae8606a1750f345d11d59d271/client/webstrates/coreOpCreator.js#L41
) using [Google's `diff-match-patch`](https://github.com/google/diff-match-patch) in other parts of the application.

If you'd want to implement it, I'd be happy to accept it, as long as it's an optional feature, so the behaviour doesn't change for people who're happy with the current implementation. How you want to make it optional is up to you (maybe as an optional `options` object passed in?). I'd also appreciate it if you'd use `diff-match-patch` instead of JSDiff as `diff-match-patch` seems to be a lot smaller than JSDiff, and I know that `diff-match-patch` works very well. To help persuade you, [here's a function that I've written which converts patches to ops](https://github.com/Webstrates/Webstrates/blob/9ddb44164110f21ae8606a1750f345d11d59d271/client/webstrates/coreOpCreator.js#L38-L62), so it should be very easy to implement.

Looking forward to your pull request! :-)

**Comment by curran** [comment]
@kbadk Thanks for the pointers and encouragement!

PR ready for review https://github.com/kbadk/json0-ot-diff/pull/5

**Comment by kbadk** [comment]
This looks great, thank you!

**Comment by curran** [comment]
Thanks for merging!

Can you please publish a new version to NPM? Thank you.

**Comment by kbadk** [comment]
Done!
